package com.sysdt.estimuladorapp.dao;

import com.sysdt.estimuladorapp.model.Administrador;
import com.sysdt.estimuladorapp.model.AdministradorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdministradorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrador
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int countByExample(AdministradorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrador
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int deleteByExample(AdministradorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrador
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrador
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int insert(Administrador record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrador
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int insertSelective(Administrador record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrador
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    List<Administrador> selectByExample(AdministradorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrador
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    Administrador selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrador
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByExampleSelective(@Param("record") Administrador record, @Param("example") AdministradorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrador
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByExample(@Param("record") Administrador record, @Param("example") AdministradorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrador
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByPrimaryKeySelective(Administrador record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrador
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByPrimaryKey(Administrador record);
}