package com.sysdt.estimuladorapp.dao;

import com.sysdt.estimuladorapp.model.Estimulador;
import com.sysdt.estimuladorapp.model.EstimuladorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EstimuladorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimulador
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int countByExample(EstimuladorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimulador
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int deleteByExample(EstimuladorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimulador
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimulador
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int insert(Estimulador record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimulador
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int insertSelective(Estimulador record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimulador
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    List<Estimulador> selectByExample(EstimuladorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimulador
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    Estimulador selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimulador
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByExampleSelective(@Param("record") Estimulador record, @Param("example") EstimuladorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimulador
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByExample(@Param("record") Estimulador record, @Param("example") EstimuladorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimulador
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByPrimaryKeySelective(Estimulador record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimulador
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByPrimaryKey(Estimulador record);
}