package com.sysdt.estimuladorapp.dao;

import com.sysdt.estimuladorapp.model.Historico;
import com.sysdt.estimuladorapp.model.HistoricoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HistoricoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int countByExample(HistoricoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int deleteByExample(HistoricoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int insert(Historico record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int insertSelective(Historico record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    List<Historico> selectByExample(HistoricoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    Historico selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByExampleSelective(@Param("record") Historico record, @Param("example") HistoricoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByExample(@Param("record") Historico record, @Param("example") HistoricoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByPrimaryKeySelective(Historico record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByPrimaryKey(Historico record);
}