package com.sysdt.estimuladorapp.dao;

import com.sysdt.estimuladorapp.model.Medico;
import com.sysdt.estimuladorapp.model.MedicoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MedicoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medico
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int countByExample(MedicoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medico
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int deleteByExample(MedicoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medico
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medico
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int insert(Medico record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medico
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int insertSelective(Medico record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medico
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    List<Medico> selectByExample(MedicoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medico
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    Medico selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medico
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByExampleSelective(@Param("record") Medico record, @Param("example") MedicoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medico
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByExample(@Param("record") Medico record, @Param("example") MedicoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medico
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByPrimaryKeySelective(Medico record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medico
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByPrimaryKey(Medico record);
}