package com.sysdt.estimuladorapp.dao;

import com.sysdt.estimuladorapp.model.Tipoparentesco;
import com.sysdt.estimuladorapp.model.TipoparentescoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TipoparentescoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipoparentesco
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int countByExample(TipoparentescoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipoparentesco
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int deleteByExample(TipoparentescoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipoparentesco
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipoparentesco
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int insert(Tipoparentesco record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipoparentesco
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int insertSelective(Tipoparentesco record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipoparentesco
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    List<Tipoparentesco> selectByExample(TipoparentescoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipoparentesco
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    Tipoparentesco selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipoparentesco
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByExampleSelective(@Param("record") Tipoparentesco record, @Param("example") TipoparentescoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipoparentesco
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByExample(@Param("record") Tipoparentesco record, @Param("example") TipoparentescoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipoparentesco
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByPrimaryKeySelective(Tipoparentesco record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipoparentesco
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByPrimaryKey(Tipoparentesco record);
}