package com.sysdt.estimuladorapp.dao;

import com.sysdt.estimuladorapp.model.Tipotelefono;
import com.sysdt.estimuladorapp.model.TipotelefonoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TipotelefonoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipotelefono
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int countByExample(TipotelefonoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipotelefono
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int deleteByExample(TipotelefonoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipotelefono
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipotelefono
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int insert(Tipotelefono record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipotelefono
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int insertSelective(Tipotelefono record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipotelefono
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    List<Tipotelefono> selectByExample(TipotelefonoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipotelefono
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    Tipotelefono selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipotelefono
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByExampleSelective(@Param("record") Tipotelefono record, @Param("example") TipotelefonoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipotelefono
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByExample(@Param("record") Tipotelefono record, @Param("example") TipotelefonoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipotelefono
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByPrimaryKeySelective(Tipotelefono record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipotelefono
     *
     * @mbggenerated Sat Aug 27 14:10:49 CDT 2016
     */
    int updateByPrimaryKey(Tipotelefono record);
}