package com.sysdt.estimuladorapp.model;

public class Administrador {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrador.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrador.nombre
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrador.apaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String apaterno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrador.amaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String amaterno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrador.idUsuario
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Integer idUsuario;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrador.id
     *
     * @return the value of administrador.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrador.id
     *
     * @param id the value for administrador.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrador.nombre
     *
     * @return the value of administrador.nombre
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrador.nombre
     *
     * @param nombre the value for administrador.nombre
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrador.apaterno
     *
     * @return the value of administrador.apaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getApaterno() {
        return apaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrador.apaterno
     *
     * @param apaterno the value for administrador.apaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrador.amaterno
     *
     * @return the value of administrador.amaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getAmaterno() {
        return amaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrador.amaterno
     *
     * @param amaterno the value for administrador.amaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrador.idUsuario
     *
     * @return the value of administrador.idUsuario
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Integer getIdUsuario() {
        return idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrador.idUsuario
     *
     * @param idUsuario the value for administrador.idUsuario
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
}