package com.sysdt.estimuladorapp.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HistoricoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public HistoricoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLatitudIsNull() {
            addCriterion("latitud is null");
            return (Criteria) this;
        }

        public Criteria andLatitudIsNotNull() {
            addCriterion("latitud is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudEqualTo(String value) {
            addCriterion("latitud =", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudNotEqualTo(String value) {
            addCriterion("latitud <>", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudGreaterThan(String value) {
            addCriterion("latitud >", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudGreaterThanOrEqualTo(String value) {
            addCriterion("latitud >=", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudLessThan(String value) {
            addCriterion("latitud <", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudLessThanOrEqualTo(String value) {
            addCriterion("latitud <=", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudLike(String value) {
            addCriterion("latitud like", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudNotLike(String value) {
            addCriterion("latitud not like", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudIn(List<String> values) {
            addCriterion("latitud in", values, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudNotIn(List<String> values) {
            addCriterion("latitud not in", values, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudBetween(String value1, String value2) {
            addCriterion("latitud between", value1, value2, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudNotBetween(String value1, String value2) {
            addCriterion("latitud not between", value1, value2, "latitud");
            return (Criteria) this;
        }

        public Criteria andLongitudIsNull() {
            addCriterion("longitud is null");
            return (Criteria) this;
        }

        public Criteria andLongitudIsNotNull() {
            addCriterion("longitud is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudEqualTo(String value) {
            addCriterion("longitud =", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudNotEqualTo(String value) {
            addCriterion("longitud <>", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudGreaterThan(String value) {
            addCriterion("longitud >", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudGreaterThanOrEqualTo(String value) {
            addCriterion("longitud >=", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudLessThan(String value) {
            addCriterion("longitud <", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudLessThanOrEqualTo(String value) {
            addCriterion("longitud <=", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudLike(String value) {
            addCriterion("longitud like", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudNotLike(String value) {
            addCriterion("longitud not like", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudIn(List<String> values) {
            addCriterion("longitud in", values, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudNotIn(List<String> values) {
            addCriterion("longitud not in", values, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudBetween(String value1, String value2) {
            addCriterion("longitud between", value1, value2, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudNotBetween(String value1, String value2) {
            addCriterion("longitud not between", value1, value2, "longitud");
            return (Criteria) this;
        }

        public Criteria andFechaInicioIsNull() {
            addCriterion("fechaInicio is null");
            return (Criteria) this;
        }

        public Criteria andFechaInicioIsNotNull() {
            addCriterion("fechaInicio is not null");
            return (Criteria) this;
        }

        public Criteria andFechaInicioEqualTo(Date value) {
            addCriterion("fechaInicio =", value, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioNotEqualTo(Date value) {
            addCriterion("fechaInicio <>", value, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioGreaterThan(Date value) {
            addCriterion("fechaInicio >", value, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioGreaterThanOrEqualTo(Date value) {
            addCriterion("fechaInicio >=", value, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioLessThan(Date value) {
            addCriterion("fechaInicio <", value, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioLessThanOrEqualTo(Date value) {
            addCriterion("fechaInicio <=", value, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioIn(List<Date> values) {
            addCriterion("fechaInicio in", values, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioNotIn(List<Date> values) {
            addCriterion("fechaInicio not in", values, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioBetween(Date value1, Date value2) {
            addCriterion("fechaInicio between", value1, value2, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioNotBetween(Date value1, Date value2) {
            addCriterion("fechaInicio not between", value1, value2, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaFinIsNull() {
            addCriterion("fechaFin is null");
            return (Criteria) this;
        }

        public Criteria andFechaFinIsNotNull() {
            addCriterion("fechaFin is not null");
            return (Criteria) this;
        }

        public Criteria andFechaFinEqualTo(Date value) {
            addCriterion("fechaFin =", value, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinNotEqualTo(Date value) {
            addCriterion("fechaFin <>", value, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinGreaterThan(Date value) {
            addCriterion("fechaFin >", value, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinGreaterThanOrEqualTo(Date value) {
            addCriterion("fechaFin >=", value, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinLessThan(Date value) {
            addCriterion("fechaFin <", value, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinLessThanOrEqualTo(Date value) {
            addCriterion("fechaFin <=", value, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinIn(List<Date> values) {
            addCriterion("fechaFin in", values, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinNotIn(List<Date> values) {
            addCriterion("fechaFin not in", values, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinBetween(Date value1, Date value2) {
            addCriterion("fechaFin between", value1, value2, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinNotBetween(Date value1, Date value2) {
            addCriterion("fechaFin not between", value1, value2, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNull() {
            addCriterion("estado is null");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNotNull() {
            addCriterion("estado is not null");
            return (Criteria) this;
        }

        public Criteria andEstadoEqualTo(Integer value) {
            addCriterion("estado =", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotEqualTo(Integer value) {
            addCriterion("estado <>", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThan(Integer value) {
            addCriterion("estado >", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThanOrEqualTo(Integer value) {
            addCriterion("estado >=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThan(Integer value) {
            addCriterion("estado <", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThanOrEqualTo(Integer value) {
            addCriterion("estado <=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoIn(List<Integer> values) {
            addCriterion("estado in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotIn(List<Integer> values) {
            addCriterion("estado not in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoBetween(Integer value1, Integer value2) {
            addCriterion("estado between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotBetween(Integer value1, Integer value2) {
            addCriterion("estado not between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaIsNull() {
            addCriterion("frecuencia is null");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaIsNotNull() {
            addCriterion("frecuencia is not null");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaEqualTo(Double value) {
            addCriterion("frecuencia =", value, "frecuencia");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaNotEqualTo(Double value) {
            addCriterion("frecuencia <>", value, "frecuencia");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaGreaterThan(Double value) {
            addCriterion("frecuencia >", value, "frecuencia");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaGreaterThanOrEqualTo(Double value) {
            addCriterion("frecuencia >=", value, "frecuencia");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaLessThan(Double value) {
            addCriterion("frecuencia <", value, "frecuencia");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaLessThanOrEqualTo(Double value) {
            addCriterion("frecuencia <=", value, "frecuencia");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaIn(List<Double> values) {
            addCriterion("frecuencia in", values, "frecuencia");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaNotIn(List<Double> values) {
            addCriterion("frecuencia not in", values, "frecuencia");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaBetween(Double value1, Double value2) {
            addCriterion("frecuencia between", value1, value2, "frecuencia");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaNotBetween(Double value1, Double value2) {
            addCriterion("frecuencia not between", value1, value2, "frecuencia");
            return (Criteria) this;
        }

        public Criteria andAmplitudIsNull() {
            addCriterion("amplitud is null");
            return (Criteria) this;
        }

        public Criteria andAmplitudIsNotNull() {
            addCriterion("amplitud is not null");
            return (Criteria) this;
        }

        public Criteria andAmplitudEqualTo(Integer value) {
            addCriterion("amplitud =", value, "amplitud");
            return (Criteria) this;
        }

        public Criteria andAmplitudNotEqualTo(Integer value) {
            addCriterion("amplitud <>", value, "amplitud");
            return (Criteria) this;
        }

        public Criteria andAmplitudGreaterThan(Integer value) {
            addCriterion("amplitud >", value, "amplitud");
            return (Criteria) this;
        }

        public Criteria andAmplitudGreaterThanOrEqualTo(Integer value) {
            addCriterion("amplitud >=", value, "amplitud");
            return (Criteria) this;
        }

        public Criteria andAmplitudLessThan(Integer value) {
            addCriterion("amplitud <", value, "amplitud");
            return (Criteria) this;
        }

        public Criteria andAmplitudLessThanOrEqualTo(Integer value) {
            addCriterion("amplitud <=", value, "amplitud");
            return (Criteria) this;
        }

        public Criteria andAmplitudIn(List<Integer> values) {
            addCriterion("amplitud in", values, "amplitud");
            return (Criteria) this;
        }

        public Criteria andAmplitudNotIn(List<Integer> values) {
            addCriterion("amplitud not in", values, "amplitud");
            return (Criteria) this;
        }

        public Criteria andAmplitudBetween(Integer value1, Integer value2) {
            addCriterion("amplitud between", value1, value2, "amplitud");
            return (Criteria) this;
        }

        public Criteria andAmplitudNotBetween(Integer value1, Integer value2) {
            addCriterion("amplitud not between", value1, value2, "amplitud");
            return (Criteria) this;
        }

        public Criteria andTiempoIsNull() {
            addCriterion("tiempo is null");
            return (Criteria) this;
        }

        public Criteria andTiempoIsNotNull() {
            addCriterion("tiempo is not null");
            return (Criteria) this;
        }

        public Criteria andTiempoEqualTo(Integer value) {
            addCriterion("tiempo =", value, "tiempo");
            return (Criteria) this;
        }

        public Criteria andTiempoNotEqualTo(Integer value) {
            addCriterion("tiempo <>", value, "tiempo");
            return (Criteria) this;
        }

        public Criteria andTiempoGreaterThan(Integer value) {
            addCriterion("tiempo >", value, "tiempo");
            return (Criteria) this;
        }

        public Criteria andTiempoGreaterThanOrEqualTo(Integer value) {
            addCriterion("tiempo >=", value, "tiempo");
            return (Criteria) this;
        }

        public Criteria andTiempoLessThan(Integer value) {
            addCriterion("tiempo <", value, "tiempo");
            return (Criteria) this;
        }

        public Criteria andTiempoLessThanOrEqualTo(Integer value) {
            addCriterion("tiempo <=", value, "tiempo");
            return (Criteria) this;
        }

        public Criteria andTiempoIn(List<Integer> values) {
            addCriterion("tiempo in", values, "tiempo");
            return (Criteria) this;
        }

        public Criteria andTiempoNotIn(List<Integer> values) {
            addCriterion("tiempo not in", values, "tiempo");
            return (Criteria) this;
        }

        public Criteria andTiempoBetween(Integer value1, Integer value2) {
            addCriterion("tiempo between", value1, value2, "tiempo");
            return (Criteria) this;
        }

        public Criteria andTiempoNotBetween(Integer value1, Integer value2) {
            addCriterion("tiempo not between", value1, value2, "tiempo");
            return (Criteria) this;
        }

        public Criteria andTipoOndaIsNull() {
            addCriterion("tipoOnda is null");
            return (Criteria) this;
        }

        public Criteria andTipoOndaIsNotNull() {
            addCriterion("tipoOnda is not null");
            return (Criteria) this;
        }

        public Criteria andTipoOndaEqualTo(Integer value) {
            addCriterion("tipoOnda =", value, "tipoOnda");
            return (Criteria) this;
        }

        public Criteria andTipoOndaNotEqualTo(Integer value) {
            addCriterion("tipoOnda <>", value, "tipoOnda");
            return (Criteria) this;
        }

        public Criteria andTipoOndaGreaterThan(Integer value) {
            addCriterion("tipoOnda >", value, "tipoOnda");
            return (Criteria) this;
        }

        public Criteria andTipoOndaGreaterThanOrEqualTo(Integer value) {
            addCriterion("tipoOnda >=", value, "tipoOnda");
            return (Criteria) this;
        }

        public Criteria andTipoOndaLessThan(Integer value) {
            addCriterion("tipoOnda <", value, "tipoOnda");
            return (Criteria) this;
        }

        public Criteria andTipoOndaLessThanOrEqualTo(Integer value) {
            addCriterion("tipoOnda <=", value, "tipoOnda");
            return (Criteria) this;
        }

        public Criteria andTipoOndaIn(List<Integer> values) {
            addCriterion("tipoOnda in", values, "tipoOnda");
            return (Criteria) this;
        }

        public Criteria andTipoOndaNotIn(List<Integer> values) {
            addCriterion("tipoOnda not in", values, "tipoOnda");
            return (Criteria) this;
        }

        public Criteria andTipoOndaBetween(Integer value1, Integer value2) {
            addCriterion("tipoOnda between", value1, value2, "tipoOnda");
            return (Criteria) this;
        }

        public Criteria andTipoOndaNotBetween(Integer value1, Integer value2) {
            addCriterion("tipoOnda not between", value1, value2, "tipoOnda");
            return (Criteria) this;
        }

        public Criteria andIdEstimuladorIsNull() {
            addCriterion("idEstimulador is null");
            return (Criteria) this;
        }

        public Criteria andIdEstimuladorIsNotNull() {
            addCriterion("idEstimulador is not null");
            return (Criteria) this;
        }

        public Criteria andIdEstimuladorEqualTo(Integer value) {
            addCriterion("idEstimulador =", value, "idEstimulador");
            return (Criteria) this;
        }

        public Criteria andIdEstimuladorNotEqualTo(Integer value) {
            addCriterion("idEstimulador <>", value, "idEstimulador");
            return (Criteria) this;
        }

        public Criteria andIdEstimuladorGreaterThan(Integer value) {
            addCriterion("idEstimulador >", value, "idEstimulador");
            return (Criteria) this;
        }

        public Criteria andIdEstimuladorGreaterThanOrEqualTo(Integer value) {
            addCriterion("idEstimulador >=", value, "idEstimulador");
            return (Criteria) this;
        }

        public Criteria andIdEstimuladorLessThan(Integer value) {
            addCriterion("idEstimulador <", value, "idEstimulador");
            return (Criteria) this;
        }

        public Criteria andIdEstimuladorLessThanOrEqualTo(Integer value) {
            addCriterion("idEstimulador <=", value, "idEstimulador");
            return (Criteria) this;
        }

        public Criteria andIdEstimuladorIn(List<Integer> values) {
            addCriterion("idEstimulador in", values, "idEstimulador");
            return (Criteria) this;
        }

        public Criteria andIdEstimuladorNotIn(List<Integer> values) {
            addCriterion("idEstimulador not in", values, "idEstimulador");
            return (Criteria) this;
        }

        public Criteria andIdEstimuladorBetween(Integer value1, Integer value2) {
            addCriterion("idEstimulador between", value1, value2, "idEstimulador");
            return (Criteria) this;
        }

        public Criteria andIdEstimuladorNotBetween(Integer value1, Integer value2) {
            addCriterion("idEstimulador not between", value1, value2, "idEstimulador");
            return (Criteria) this;
        }

        public Criteria andIdPacienteIsNull() {
            addCriterion("idPaciente is null");
            return (Criteria) this;
        }

        public Criteria andIdPacienteIsNotNull() {
            addCriterion("idPaciente is not null");
            return (Criteria) this;
        }

        public Criteria andIdPacienteEqualTo(Integer value) {
            addCriterion("idPaciente =", value, "idPaciente");
            return (Criteria) this;
        }

        public Criteria andIdPacienteNotEqualTo(Integer value) {
            addCriterion("idPaciente <>", value, "idPaciente");
            return (Criteria) this;
        }

        public Criteria andIdPacienteGreaterThan(Integer value) {
            addCriterion("idPaciente >", value, "idPaciente");
            return (Criteria) this;
        }

        public Criteria andIdPacienteGreaterThanOrEqualTo(Integer value) {
            addCriterion("idPaciente >=", value, "idPaciente");
            return (Criteria) this;
        }

        public Criteria andIdPacienteLessThan(Integer value) {
            addCriterion("idPaciente <", value, "idPaciente");
            return (Criteria) this;
        }

        public Criteria andIdPacienteLessThanOrEqualTo(Integer value) {
            addCriterion("idPaciente <=", value, "idPaciente");
            return (Criteria) this;
        }

        public Criteria andIdPacienteIn(List<Integer> values) {
            addCriterion("idPaciente in", values, "idPaciente");
            return (Criteria) this;
        }

        public Criteria andIdPacienteNotIn(List<Integer> values) {
            addCriterion("idPaciente not in", values, "idPaciente");
            return (Criteria) this;
        }

        public Criteria andIdPacienteBetween(Integer value1, Integer value2) {
            addCriterion("idPaciente between", value1, value2, "idPaciente");
            return (Criteria) this;
        }

        public Criteria andIdPacienteNotBetween(Integer value1, Integer value2) {
            addCriterion("idPaciente not between", value1, value2, "idPaciente");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table historico
     *
     * @mbggenerated do_not_delete_during_merge Sat Aug 27 13:56:24 CDT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table historico
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}