package com.sysdt.estimuladorapp.model;

import java.util.Date;

public class Historico {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historico.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historico.latitud
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String latitud;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historico.longitud
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String longitud;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historico.fechaInicio
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Date fechaInicio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historico.fechaFin
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Date fechaFin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historico.estado
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Integer estado;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historico.frecuencia
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Double frecuencia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historico.amplitud
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Integer amplitud;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historico.tiempo
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Integer tiempo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historico.tipoOnda
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Integer tipoOnda;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historico.idEstimulador
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Integer idEstimulador;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historico.idPaciente
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Integer idPaciente;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historico.id
     *
     * @return the value of historico.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historico.id
     *
     * @param id the value for historico.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historico.latitud
     *
     * @return the value of historico.latitud
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getLatitud() {
        return latitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historico.latitud
     *
     * @param latitud the value for historico.latitud
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setLatitud(String latitud) {
        this.latitud = latitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historico.longitud
     *
     * @return the value of historico.longitud
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getLongitud() {
        return longitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historico.longitud
     *
     * @param longitud the value for historico.longitud
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setLongitud(String longitud) {
        this.longitud = longitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historico.fechaInicio
     *
     * @return the value of historico.fechaInicio
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Date getFechaInicio() {
        return fechaInicio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historico.fechaInicio
     *
     * @param fechaInicio the value for historico.fechaInicio
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historico.fechaFin
     *
     * @return the value of historico.fechaFin
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Date getFechaFin() {
        return fechaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historico.fechaFin
     *
     * @param fechaFin the value for historico.fechaFin
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historico.estado
     *
     * @return the value of historico.estado
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Integer getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historico.estado
     *
     * @param estado the value for historico.estado
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setEstado(Integer estado) {
        this.estado = estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historico.frecuencia
     *
     * @return the value of historico.frecuencia
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Double getFrecuencia() {
        return frecuencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historico.frecuencia
     *
     * @param frecuencia the value for historico.frecuencia
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setFrecuencia(Double frecuencia) {
        this.frecuencia = frecuencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historico.amplitud
     *
     * @return the value of historico.amplitud
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Integer getAmplitud() {
        return amplitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historico.amplitud
     *
     * @param amplitud the value for historico.amplitud
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setAmplitud(Integer amplitud) {
        this.amplitud = amplitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historico.tiempo
     *
     * @return the value of historico.tiempo
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Integer getTiempo() {
        return tiempo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historico.tiempo
     *
     * @param tiempo the value for historico.tiempo
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setTiempo(Integer tiempo) {
        this.tiempo = tiempo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historico.tipoOnda
     *
     * @return the value of historico.tipoOnda
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Integer getTipoOnda() {
        return tipoOnda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historico.tipoOnda
     *
     * @param tipoOnda the value for historico.tipoOnda
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setTipoOnda(Integer tipoOnda) {
        this.tipoOnda = tipoOnda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historico.idEstimulador
     *
     * @return the value of historico.idEstimulador
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Integer getIdEstimulador() {
        return idEstimulador;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historico.idEstimulador
     *
     * @param idEstimulador the value for historico.idEstimulador
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setIdEstimulador(Integer idEstimulador) {
        this.idEstimulador = idEstimulador;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historico.idPaciente
     *
     * @return the value of historico.idPaciente
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Integer getIdPaciente() {
        return idPaciente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historico.idPaciente
     *
     * @param idPaciente the value for historico.idPaciente
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }
}