package com.sysdt.estimuladorapp.model;

public class Medico {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medico.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medico.nombre
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medico.apaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String apaterno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medico.amaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String amaterno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medico.institucion
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String institucion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medico.consultorio
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Integer consultorio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medico.especialidad
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String especialidad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medico.cedula
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String cedula;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medico.idUsuario
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Integer idUsuario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medico.enabled
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Boolean enabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medico.id
     *
     * @return the value of medico.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medico.id
     *
     * @param id the value for medico.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medico.nombre
     *
     * @return the value of medico.nombre
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medico.nombre
     *
     * @param nombre the value for medico.nombre
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medico.apaterno
     *
     * @return the value of medico.apaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getApaterno() {
        return apaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medico.apaterno
     *
     * @param apaterno the value for medico.apaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medico.amaterno
     *
     * @return the value of medico.amaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getAmaterno() {
        return amaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medico.amaterno
     *
     * @param amaterno the value for medico.amaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medico.institucion
     *
     * @return the value of medico.institucion
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getInstitucion() {
        return institucion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medico.institucion
     *
     * @param institucion the value for medico.institucion
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setInstitucion(String institucion) {
        this.institucion = institucion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medico.consultorio
     *
     * @return the value of medico.consultorio
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Integer getConsultorio() {
        return consultorio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medico.consultorio
     *
     * @param consultorio the value for medico.consultorio
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setConsultorio(Integer consultorio) {
        this.consultorio = consultorio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medico.especialidad
     *
     * @return the value of medico.especialidad
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getEspecialidad() {
        return especialidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medico.especialidad
     *
     * @param especialidad the value for medico.especialidad
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medico.cedula
     *
     * @return the value of medico.cedula
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getCedula() {
        return cedula;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medico.cedula
     *
     * @param cedula the value for medico.cedula
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medico.idUsuario
     *
     * @return the value of medico.idUsuario
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Integer getIdUsuario() {
        return idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medico.idUsuario
     *
     * @param idUsuario the value for medico.idUsuario
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medico.enabled
     *
     * @return the value of medico.enabled
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medico.enabled
     *
     * @param enabled the value for medico.enabled
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}