package com.sysdt.estimuladorapp.model;

public class Paciente {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paciente.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paciente.nombre
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paciente.apaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String apaterno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paciente.amaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String amaterno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paciente.idUsuario
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Integer idUsuario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paciente.direccion
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String direccion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paciente.email
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paciente.enabled
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Boolean enabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paciente.id
     *
     * @return the value of paciente.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paciente.id
     *
     * @param id the value for paciente.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paciente.nombre
     *
     * @return the value of paciente.nombre
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paciente.nombre
     *
     * @param nombre the value for paciente.nombre
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paciente.apaterno
     *
     * @return the value of paciente.apaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getApaterno() {
        return apaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paciente.apaterno
     *
     * @param apaterno the value for paciente.apaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paciente.amaterno
     *
     * @return the value of paciente.amaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getAmaterno() {
        return amaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paciente.amaterno
     *
     * @param amaterno the value for paciente.amaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paciente.idUsuario
     *
     * @return the value of paciente.idUsuario
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Integer getIdUsuario() {
        return idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paciente.idUsuario
     *
     * @param idUsuario the value for paciente.idUsuario
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paciente.direccion
     *
     * @return the value of paciente.direccion
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paciente.direccion
     *
     * @param direccion the value for paciente.direccion
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paciente.email
     *
     * @return the value of paciente.email
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paciente.email
     *
     * @param email the value for paciente.email
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paciente.enabled
     *
     * @return the value of paciente.enabled
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paciente.enabled
     *
     * @param enabled the value for paciente.enabled
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}