package com.sysdt.estimuladorapp.model;

public class Responsable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column responsable.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column responsable.nombre
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column responsable.apaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String apaterno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column responsable.amaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String amaterno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column responsable.idTipoParentesco
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Integer idTipoParentesco;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column responsable.idPaciente
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Integer idPaciente;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column responsable.id
     *
     * @return the value of responsable.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column responsable.id
     *
     * @param id the value for responsable.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column responsable.nombre
     *
     * @return the value of responsable.nombre
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column responsable.nombre
     *
     * @param nombre the value for responsable.nombre
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column responsable.apaterno
     *
     * @return the value of responsable.apaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getApaterno() {
        return apaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column responsable.apaterno
     *
     * @param apaterno the value for responsable.apaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column responsable.amaterno
     *
     * @return the value of responsable.amaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getAmaterno() {
        return amaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column responsable.amaterno
     *
     * @param amaterno the value for responsable.amaterno
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column responsable.idTipoParentesco
     *
     * @return the value of responsable.idTipoParentesco
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Integer getIdTipoParentesco() {
        return idTipoParentesco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column responsable.idTipoParentesco
     *
     * @param idTipoParentesco the value for responsable.idTipoParentesco
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setIdTipoParentesco(Integer idTipoParentesco) {
        this.idTipoParentesco = idTipoParentesco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column responsable.idPaciente
     *
     * @return the value of responsable.idPaciente
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Integer getIdPaciente() {
        return idPaciente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column responsable.idPaciente
     *
     * @param idPaciente the value for responsable.idPaciente
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }
}