package com.sysdt.estimuladorapp.model;

public class Telefono {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telefono.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telefono.numero
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String numero;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telefono.idTipoTelefono
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Integer idTipoTelefono;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telefono.idUsuario
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Integer idUsuario;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telefono.id
     *
     * @return the value of telefono.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telefono.id
     *
     * @param id the value for telefono.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telefono.numero
     *
     * @return the value of telefono.numero
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getNumero() {
        return numero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telefono.numero
     *
     * @param numero the value for telefono.numero
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setNumero(String numero) {
        this.numero = numero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telefono.idTipoTelefono
     *
     * @return the value of telefono.idTipoTelefono
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Integer getIdTipoTelefono() {
        return idTipoTelefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telefono.idTipoTelefono
     *
     * @param idTipoTelefono the value for telefono.idTipoTelefono
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setIdTipoTelefono(Integer idTipoTelefono) {
        this.idTipoTelefono = idTipoTelefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telefono.idUsuario
     *
     * @return the value of telefono.idUsuario
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Integer getIdUsuario() {
        return idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telefono.idUsuario
     *
     * @param idUsuario the value for telefono.idUsuario
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
}