package com.sysdt.estimuladorapp.model;

import java.util.ArrayList;
import java.util.List;

public class TelefonoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table telefono
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table telefono
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table telefono
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telefono
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public TelefonoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telefono
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telefono
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telefono
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telefono
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telefono
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telefono
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telefono
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telefono
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telefono
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telefono
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table telefono
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNumeroIsNull() {
            addCriterion("numero is null");
            return (Criteria) this;
        }

        public Criteria andNumeroIsNotNull() {
            addCriterion("numero is not null");
            return (Criteria) this;
        }

        public Criteria andNumeroEqualTo(String value) {
            addCriterion("numero =", value, "numero");
            return (Criteria) this;
        }

        public Criteria andNumeroNotEqualTo(String value) {
            addCriterion("numero <>", value, "numero");
            return (Criteria) this;
        }

        public Criteria andNumeroGreaterThan(String value) {
            addCriterion("numero >", value, "numero");
            return (Criteria) this;
        }

        public Criteria andNumeroGreaterThanOrEqualTo(String value) {
            addCriterion("numero >=", value, "numero");
            return (Criteria) this;
        }

        public Criteria andNumeroLessThan(String value) {
            addCriterion("numero <", value, "numero");
            return (Criteria) this;
        }

        public Criteria andNumeroLessThanOrEqualTo(String value) {
            addCriterion("numero <=", value, "numero");
            return (Criteria) this;
        }

        public Criteria andNumeroLike(String value) {
            addCriterion("numero like", value, "numero");
            return (Criteria) this;
        }

        public Criteria andNumeroNotLike(String value) {
            addCriterion("numero not like", value, "numero");
            return (Criteria) this;
        }

        public Criteria andNumeroIn(List<String> values) {
            addCriterion("numero in", values, "numero");
            return (Criteria) this;
        }

        public Criteria andNumeroNotIn(List<String> values) {
            addCriterion("numero not in", values, "numero");
            return (Criteria) this;
        }

        public Criteria andNumeroBetween(String value1, String value2) {
            addCriterion("numero between", value1, value2, "numero");
            return (Criteria) this;
        }

        public Criteria andNumeroNotBetween(String value1, String value2) {
            addCriterion("numero not between", value1, value2, "numero");
            return (Criteria) this;
        }

        public Criteria andIdTipoTelefonoIsNull() {
            addCriterion("idTipoTelefono is null");
            return (Criteria) this;
        }

        public Criteria andIdTipoTelefonoIsNotNull() {
            addCriterion("idTipoTelefono is not null");
            return (Criteria) this;
        }

        public Criteria andIdTipoTelefonoEqualTo(Integer value) {
            addCriterion("idTipoTelefono =", value, "idTipoTelefono");
            return (Criteria) this;
        }

        public Criteria andIdTipoTelefonoNotEqualTo(Integer value) {
            addCriterion("idTipoTelefono <>", value, "idTipoTelefono");
            return (Criteria) this;
        }

        public Criteria andIdTipoTelefonoGreaterThan(Integer value) {
            addCriterion("idTipoTelefono >", value, "idTipoTelefono");
            return (Criteria) this;
        }

        public Criteria andIdTipoTelefonoGreaterThanOrEqualTo(Integer value) {
            addCriterion("idTipoTelefono >=", value, "idTipoTelefono");
            return (Criteria) this;
        }

        public Criteria andIdTipoTelefonoLessThan(Integer value) {
            addCriterion("idTipoTelefono <", value, "idTipoTelefono");
            return (Criteria) this;
        }

        public Criteria andIdTipoTelefonoLessThanOrEqualTo(Integer value) {
            addCriterion("idTipoTelefono <=", value, "idTipoTelefono");
            return (Criteria) this;
        }

        public Criteria andIdTipoTelefonoIn(List<Integer> values) {
            addCriterion("idTipoTelefono in", values, "idTipoTelefono");
            return (Criteria) this;
        }

        public Criteria andIdTipoTelefonoNotIn(List<Integer> values) {
            addCriterion("idTipoTelefono not in", values, "idTipoTelefono");
            return (Criteria) this;
        }

        public Criteria andIdTipoTelefonoBetween(Integer value1, Integer value2) {
            addCriterion("idTipoTelefono between", value1, value2, "idTipoTelefono");
            return (Criteria) this;
        }

        public Criteria andIdTipoTelefonoNotBetween(Integer value1, Integer value2) {
            addCriterion("idTipoTelefono not between", value1, value2, "idTipoTelefono");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIsNull() {
            addCriterion("idUsuario is null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIsNotNull() {
            addCriterion("idUsuario is not null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioEqualTo(Integer value) {
            addCriterion("idUsuario =", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioNotEqualTo(Integer value) {
            addCriterion("idUsuario <>", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGreaterThan(Integer value) {
            addCriterion("idUsuario >", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGreaterThanOrEqualTo(Integer value) {
            addCriterion("idUsuario >=", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioLessThan(Integer value) {
            addCriterion("idUsuario <", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioLessThanOrEqualTo(Integer value) {
            addCriterion("idUsuario <=", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIn(List<Integer> values) {
            addCriterion("idUsuario in", values, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioNotIn(List<Integer> values) {
            addCriterion("idUsuario not in", values, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioBetween(Integer value1, Integer value2) {
            addCriterion("idUsuario between", value1, value2, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioNotBetween(Integer value1, Integer value2) {
            addCriterion("idUsuario not between", value1, value2, "idUsuario");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table telefono
     *
     * @mbggenerated do_not_delete_during_merge Sat Aug 27 13:56:24 CDT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table telefono
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}