package com.sysdt.estimuladorapp.model;

public class Tipoonda {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tipoonda.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tipoonda.tipo
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String tipo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tipoonda.id
     *
     * @return the value of tipoonda.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tipoonda.id
     *
     * @param id the value for tipoonda.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tipoonda.tipo
     *
     * @return the value of tipoonda.tipo
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tipoonda.tipo
     *
     * @param tipo the value for tipoonda.tipo
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
}