package com.sysdt.estimuladorapp.model;

public class Usuario {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.usuario
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String usuario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.password
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.token
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.idTipoUsuario
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    private Integer idTipoUsuario;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.id
     *
     * @return the value of usuario.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.id
     *
     * @param id the value for usuario.id
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.usuario
     *
     * @return the value of usuario.usuario
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getUsuario() {
        return usuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.usuario
     *
     * @param usuario the value for usuario.usuario
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.password
     *
     * @return the value of usuario.password
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.password
     *
     * @param password the value for usuario.password
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.token
     *
     * @return the value of usuario.token
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.token
     *
     * @param token the value for usuario.token
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.idTipoUsuario
     *
     * @return the value of usuario.idTipoUsuario
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public Integer getIdTipoUsuario() {
        return idTipoUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.idTipoUsuario
     *
     * @param idTipoUsuario the value for usuario.idTipoUsuario
     *
     * @mbggenerated Sat Aug 27 13:56:24 CDT 2016
     */
    public void setIdTipoUsuario(Integer idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
}